name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Debug APK Directly
        run: |
          ROOT_DIR=$(find . -name "settings.gradle.kts" -o -name "settings.gradle" | head -n 1 | xargs dirname)
          cd "$ROOT_DIR"
          chmod +x gradlew
          
          # রিলিজ সাইনিং এরর এড়াতে সরাসরি ডেবাক এ্যাসেম্বল কমান্ড রান করা
          ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Upload Finished APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: "**/build/outputs/apk/debug/*.apk"
          if-no-files-found: error
